module Kuhsaft
  require 'kuhsaft/engine'
  require 'kuhsaft/orderable'
  require 'kuhsaft/translatable'
  require 'kuhsaft/searchable'
  require 'kuhsaft/brick_list'
  require 'kuhsaft/partial_extractor'
  require 'simple_form'
  require 'carrierwave'
  require 'rdiscount'
  require 'compass'
  require 'compass-rails'
  require 'jquery-rails'
  require 'ancestry'
  require 'bootstrap-sass'
  require 'haml'
  require 'ckeditor'
end
